export const workImage = [
  {
    id: 1,
    src: "./test-7/gallery/Work/Elvira/Elvira1.jpg",
    alt: "Elvira.jpg",
    name: "Эля",
    images: [
      { src: "./test-7/gallery/Work/Elvira/Elvira1.jpg", alt: "Elvira.jpg" },
      { src: "./test-7/gallery/Work/Elvira/Elvira2.jpg", alt: "Elvira.jpg" },
      { src: "./test-7/gallery/Work/Elvira/Elvira3.jpg", alt: "Elvira.jpg" },
      { src: "./test-7/gallery/Work/Elvira/Elvira4.jpg", alt: "Elvira.jpg" },
      { src: "./test-7/gallery/Work/Elvira/Elvira5.jpg", alt: "Elvira.jpg" },
      { src: "./test-7/gallery/Work/Elvira/Elvira6.jpg", alt: "Elvira.jpg" },
      { src: "./test-7/gallery/Work/Elvira/Elvira7.jpg", alt: "Elvira.jpg" },
      { src: "./test-7/gallery/Work/Elvira/Elvira8.jpg", alt: "Elvira.jpg" },
      { src: "./test-7/gallery/Work/Elvira/Elvira9.jpg", alt: "Elvira.jpg" },
      { src: "./test-7/gallery/Work/Elvira/Elvira10.jpg", alt: "Elvira.jpg" },
    ],
  },
  {
    id: 2,
    src: "./test-7/gallery/Work/Dasha/Dasha1.jpg",
    alt: "Dasha.jpg",
    name: "Даша",
    images: [
      { src: "./test-7/gallery/Work/Dasha/Dasha1.jpg", alt: "Dasha.jpg" },
      { src: "./test-7/gallery/Work/Dasha/Dasha2.jpg", alt: "Dasha.jpg" },
      { src: "./test-7/gallery/Work/Dasha/Dasha3.jpg", alt: "Dasha.jpg" },
      { src: "./test-7/gallery/Work/Dasha/Dasha4.jpg", alt: "Dasha.jpg" },
      { src: "./test-7/gallery/Work/Dasha/Dasha5.jpg", alt: "Dasha.jpg" },
      { src: "./test-7/gallery/Work/Dasha/Dasha7.jpg", alt: "Dasha.jpg" },
      { src: "./test-7/gallery/Work/Dasha/Dasha8.jpg", alt: "Dasha.jpg" },
      { src: "./test-7/gallery/Work/Dasha/Dasha9.jpg", alt: "Dasha.jpg" },
      { src: "./test-7/gallery/Work/Dasha/Dasha10.jpg", alt: "Dasha.jpg" },
    ],
  },
  {
    id: 3,
    src: "./test-7/gallery/Work/Dopey/Nikita Punk1.jpg",
    alt: "Nikita.jpg",
    name: "Dopey",
    images: [
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk1.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk2.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk3.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk4.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk5.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk6.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk7.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk8.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk9.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk10.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk11.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk12.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk13.jpg", alt: "Nikita.jpg" },
      { src: "./test-7/gallery/Work/Dopey/Nikita Punk14.jpg", alt: "Nikita.jpg" },
    ],
  },
  {
    id: 4,
    src: "./test-7/gallery/Work/Alexandra/Alexandra1.jpg",
    alt: "Александра.jpg",
    name: "Саша",
    images: [
      { src: "./test-7/gallery/Work/Alexandra/Alexandra1.jpg", alt: "Александра.jpg" },
      { src: "./test-7/gallery/Work/Alexandra/Alexandra2.jpg", alt: "Александра.jpg" },
      { src: "./test-7/gallery/Work/Alexandra/Alexandra3.jpg", alt: "Александра.jpg" },
      { src: "./test-7/gallery/Work/Alexandra/Alexandra4.jpg", alt: "Александра.jpg" },
    ],
  },
  {
    id: 5,
    src: "./test-7/gallery/Work/Dima/Dima1.jpg",
    alt: "Dima.jpg",
    name: "Дима",
    images: [
      { src: "./test-7/gallery/Work/Dima/Dima1.jpg", alt: "Dima.jpg" },
      { src: "./test-7/gallery/Work/Dima/Dima2.jpg", alt: "Dima.jpg" },
      { src: "./test-7/gallery/Work/Dima/Dima3.jpg", alt: "Dima.jpg" },
      { src: "./test-7/gallery/Work/Dima/Dima4.jpg", alt: "Dima.jpg" },
      { src: "./test-7/gallery/Work/Dima/Dima5.jpg", alt: "Dima.jpg" },
    ],
  },
  {
    id: 6,
    src: "./test-7/gallery/Work/RHDA2017/RHDA1.jpg",
    alt: "Dima.jpg",
    name: "RHDA 2017",
    images: [
      { src: "./test-7/gallery/Work/RHDA2017/RHDA1.jpg", alt: "RHDA.jpg" },
      { src: "./test-7/gallery/Work/RHDA2017/RHDA2.jpg", alt: "RHDA.jpg" },
      { src: "./test-7/gallery/Work/RHDA2017/RHDA3.jpg", alt: "RHDA.jpg" },
      { src: "./test-7/gallery/Work/RHDA2017/RHDA4.jpg", alt: "RHDA.jpg" },
    ],
  },
];

export const personalImage = [
  { id: 1, src: "./test-7/gallery/Personal/Per-1.jpg", alt: "per-1.jpg" },
  { id: 2, src: "./test-7/gallery/Personal/Per-2.jpg", alt: "per-1.jpg" },
  { id: 3, src: "./test-7/gallery/Personal/Per-3.jpg", alt: "per-1.jpg" },
  { id: 4, src: "./test-7/gallery/Personal/Per-4.jpg", alt: "per-1.jpg" },
  { id: 5, src: "./test-7/gallery/Personal/Per-5.jpg", alt: "per-1.jpg" },
  { id: 6, src: "./test-7/gallery/Personal/Per-6.jpg", alt: "per-1.jpg" },
  { id: 7, src: "./test-7/gallery/Personal/Per-8.jpg", alt: "per-1.jpg" },
  { id: 8, src: "./test-7/gallery/Personal/Per-7.jpg", alt: "per-1.jpg" },
  { id: 9, src: "./test-7/gallery/Personal/Per-9.jpg", alt: "per-1.jpg" },
  { id: 10, src: "./test-7/gallery/Personal/Per-10.jpg", alt: "per-1.jpg" },
  { id: 11, src: "./test-7/gallery/Personal/Per-11.jpg", alt: "per-1.jpg" },
  { id: 12, src: "./test-7/gallery/Personal/Per-12.jpg", alt: "per-1.jpg" },
  { id: 13, src: "./test-7/gallery/Personal/Per-13.jpg", alt: "per-1.jpg" },
  { id: 14, src: "./test-7/gallery/Personal/Per-14.jpg", alt: "per-1.jpg" },
  { id: 15, src: "./test-7/gallery/Personal/Per-15.jpg", alt: "per-1.jpg" },
  { id: 16, src: "./test-7/gallery/Personal/Per-16.jpg", alt: "per-1.jpg" },
  { id: 17, src: "./test-7/gallery/Personal/Per-17.jpg", alt: "per-1.jpg" },
  { id: 18, src: "./test-7/gallery/Personal/Per-18.jpg", alt: "per-1.jpg" },
  { id: 19, src: "./test-7/gallery/Personal/Per-19.jpg", alt: "per-1.jpg" },
  { id: 21, src: "./test-7/gallery/Personal/Per-20.jpg", alt: "per-1.jpg" },
  { id: 21, src: "./test-7/gallery/Personal/Per-21.jpg", alt: "per-1.jpg" },
  { id: 22, src: "./test-7/gallery/Personal/Per-22.jpg", alt: "per-1.jpg" },
  { id: 23, src: "./test-7/gallery/Personal/Per-23.jpg", alt: "per-1.jpg" },
  { id: 24, src: "./test-7/gallery/Personal/Per-24.jpg", alt: "per-1.jpg" },
  { id: 25, src: "./test-7/gallery/Personal/Per-25.jpg", alt: "per-1.jpg" },
];
export const retouchImage = [
  {
    srcBefore: "./test-7/gallery/Retouche/NikitaPunkbefore.jpg",
    srcAfter: "./test-7/gallery/Retouche/NikitaPunkafter.jpg",
  },
  {
    srcBefore: "./test-7/gallery/Retouche/DSC8387-before.jpg",
    srcAfter: "./test-7/gallery/Retouche/DSC8387-after.jpg",
  },
  {
    srcBefore: "./test-7/gallery/Retouche/DSC_3101-before.jpg",
    srcAfter: "./test-7/gallery/Retouche/DSC_3101-after.jpg",
  },
  {
    srcBefore: "./test-7/gallery/Retouche/RHDA0612-before.jpg",
    srcAfter: "./test-7/gallery/Retouche/RHDA0612-after.jpg",
  },
];

export const ABOUT = { src: "./test-7/gallery/Foto-about.jpg" };